console.log("********Step First*******");
var myFullName;
console.log(myFullName);
myFullName = "Satyavan Lokhande";
console.log(myFullName);
myFullName = "Satyavan Vilas Lokhande";
console.log(myFullName);
console.log("*********Step Second********");
var myLove = "I love only JS";
console.log(myLove);
console.log("*********Step Third********");
var firstName = "Satyavan";
var lastName = "Lokhande";
var age = "22";
var address = "Dighanchi";
var pincode = "415315";
var gender = "Male";
var isMarried = "No";
console.log(firstName, lastName, age, address, pincode, gender, isMarried);
